export const domainName = 'episodes';

export const GET_EPISODES_SUCCESS = `${domainName}://GET_EPISODES_SUCCESS`;
export const GET_EPISODES_FAILED = `${domainName}://GET_EPISODES_FAILED`;
export const GET_EPISODES_FETCHED = `${domainName}://GET_EPISODES_FETCHED`;
export const GET_EPISODE_DETAILS_SUCCESS = `${domainName}://GET_EPISODE_DETAILS_SUCCESS`;
export const GET_EPISODE_DETAILS_FAILED = `${domainName}://GET_EPISODE_DETAILS_FAILED`;

export default {
  domainName,
  GET_EPISODES_SUCCESS,
  GET_EPISODES_FAILED,
  GET_EPISODES_FETCHED,
  GET_EPISODE_DETAILS_SUCCESS,
  GET_EPISODE_DETAILS_FAILED,
};
